# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include_dir_merge_list templates/

recorder:
  purge_keep_days: 30
  auto_purge: true

rest_command:
  resend_email:
    url: "https://api.resend.com/emails"
    method: POST
    headers:
      Authorization: !secret resend_api_key_header
      Content-Type: "application/json"
    payload: >
      {
        "from": "homeassistant@realdeep.net",
        "to": ["{{ recipient }}"],
        "subject": "{{ subject }}",
        "html": {{ html | tojson }}
      }

  log_to_notion:
    url: !secret notion_webhook_url
    method: POST
    headers:
      Content-Type: "application/json"
    payload: >
      {{ payload }}

  slack_webhook_prod:
    url: !secret make_webhook_prod_url
    method: POST
    headers:
      Content-Type: "application/json"
    payload: >
      {{ payload }}

  milo_dev_event:
    url: "http://192.168.0.18:5001/ha/event"
    method: POST
    headers:
      Content-Type: "application/json"
    payload: >
      {
        "entity": "{{ entity }}",
        "old": "{{ old }}",
        "new": "{{ new }}"
      }

  milo_prod_event:
    url: "http://192.168.0.17:5001/ha/event"
    method: POST
    headers:
      Content-Type: "application/json"
    payload: >
      {
        "entity": "{{ entity }}",
        "old": "{{ old }}",
        "new": "{{ new }}"
      }

shell_command:
  uptimerobot_pause: >
    curl -X POST https://api.uptimerobot.com/v2/editMonitor
    -H "Content-Type: application/x-www-form-urlencoded"
    --data "api_key={{ states('input_text.uptimerobot_api_key') }}&id=802207036&status=0"

  uptimerobot_resume: >
    curl -X POST https://api.uptimerobot.com/v2/editMonitor
    -H "Content-Type: application/x-www-form-urlencoded"
    --data "api_key={{ states('input_text.uptimerobot_api_key') }}&id=802207036&status=1"

input_select:
  milo_target:
    name: Milo Target Environment
    options:
      - dev
      - prod
    initial: dev

milo_security: !include milo_security.yaml
